# Generated by Django 3.2.7 on 2021-09-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210907_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
